package mdhim;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1320</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public class index_manifest_t extends StructObject {
	static {
		BridJ.register();
	}
	/** The type of key */
	@Field(0) 
	public int key_type() {
		return this.io.getIntField(this, 0);
	}
	/** The type of key */
	@Field(0) 
	public index_manifest_t key_type(int key_type) {
		this.io.setIntField(this, 0, key_type);
		return this;
	}
	/**
	 * The type of index <br>
	 * (PRIMARY_INDEX, SECONDARY_INDEX)
	 */
	@Field(1) 
	public int index_type() {
		return this.io.getIntField(this, 1);
	}
	/**
	 * The type of index <br>
	 * (PRIMARY_INDEX, SECONDARY_INDEX)
	 */
	@Field(1) 
	public index_manifest_t index_type(int index_type) {
		this.io.setIntField(this, 1, index_type);
		return this;
	}
	/** The id of the index in the hash table */
	@Field(2) 
	public int index_id() {
		return this.io.getIntField(this, 2);
	}
	/** The id of the index in the hash table */
	@Field(2) 
	public index_manifest_t index_id(int index_id) {
		this.io.setIntField(this, 2, index_id);
		return this;
	}
	@Field(3) 
	public int primary_id() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public index_manifest_t primary_id(int primary_id) {
		this.io.setIntField(this, 3, primary_id);
		return this;
	}
	@Field(4) 
	public int db_type() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public index_manifest_t db_type(int db_type) {
		this.io.setIntField(this, 4, db_type);
		return this;
	}
	@Field(5) 
	public int num_rangesrvs() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public index_manifest_t num_rangesrvs(int num_rangesrvs) {
		this.io.setIntField(this, 5, num_rangesrvs);
		return this;
	}
	@Field(6) 
	public int rangesrv_factor() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public index_manifest_t rangesrv_factor(int rangesrv_factor) {
		this.io.setIntField(this, 6, rangesrv_factor);
		return this;
	}
	@Field(7) 
	public long slice_size() {
		return this.io.getLongField(this, 7);
	}
	@Field(7) 
	public index_manifest_t slice_size(long slice_size) {
		this.io.setLongField(this, 7, slice_size);
		return this;
	}
	@Field(8) 
	public int num_nodes() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public index_manifest_t num_nodes(int num_nodes) {
		this.io.setIntField(this, 8, num_nodes);
		return this;
	}
	@Field(9) 
	public int local_server_rank() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public index_manifest_t local_server_rank(int local_server_rank) {
		this.io.setIntField(this, 9, local_server_rank);
		return this;
	}
	public index_manifest_t() {
		super();
	}
	public index_manifest_t(Pointer pointer) {
		super(pointer);
	}
}
