package mdhim;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Bulk get receive message<br>
 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1159</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public class mdhim_bgetrm_t extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int mtype() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public mdhim_bgetrm_t mtype(int mtype) {
		this.io.setIntField(this, 0, mtype);
		return this;
	}
	@Field(1) 
	public int server_rank() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public mdhim_bgetrm_t server_rank(int server_rank) {
		this.io.setIntField(this, 1, server_rank);
		return this;
	}
	@Field(2) 
	public int size() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public mdhim_bgetrm_t size(int size) {
		this.io.setIntField(this, 2, size);
		return this;
	}
	@Field(3) 
	public int index() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public mdhim_bgetrm_t index(int index) {
		this.io.setIntField(this, 3, index);
		return this;
	}
	@Field(4) 
	public int index_type() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public mdhim_bgetrm_t index_type(int index_type) {
		this.io.setIntField(this, 4, index_type);
		return this;
	}
	@Field(5) 
	public int error() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public mdhim_bgetrm_t error(int error) {
		this.io.setIntField(this, 5, error);
		return this;
	}
	/** C type : char[1] */
	@Array({1}) 
	@Field(6) 
	public Pointer<Byte > blah() {
		return this.io.getPointerField(this, 6);
	}
	@Field(7) 
	public int num_keys() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public mdhim_bgetrm_t num_keys(int num_keys) {
		this.io.setIntField(this, 7, num_keys);
		return this;
	}
	/** C type : void** */
	@Field(8) 
	public Pointer<Pointer<? > > keys() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : void** */
	@Field(8) 
	public mdhim_bgetrm_t keys(Pointer<Pointer<? > > keys) {
		this.io.setPointerField(this, 8, keys);
		return this;
	}
	/** C type : int* */
	@Field(9) 
	public Pointer<Integer > key_lens() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : int* */
	@Field(9) 
	public mdhim_bgetrm_t key_lens(Pointer<Integer > key_lens) {
		this.io.setPointerField(this, 9, key_lens);
		return this;
	}
	/** C type : void** */
	@Field(10) 
	public Pointer<Pointer<? > > values() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : void** */
	@Field(10) 
	public mdhim_bgetrm_t values(Pointer<Pointer<? > > values) {
		this.io.setPointerField(this, 10, values);
		return this;
	}
	/** C type : int* */
	@Field(11) 
	public Pointer<Integer > value_lens() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : int* */
	@Field(11) 
	public mdhim_bgetrm_t value_lens(Pointer<Integer > value_lens) {
		this.io.setPointerField(this, 11, value_lens);
		return this;
	}
	/** C type : mdhim_bgetrm_t* */
	@Field(12) 
	public Pointer<mdhim_bgetrm_t > next() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : mdhim_bgetrm_t* */
	@Field(12) 
	public mdhim_bgetrm_t next(Pointer<mdhim_bgetrm_t > next) {
		this.io.setPointerField(this, 12, next);
		return this;
	}
	public mdhim_bgetrm_t() {
		super();
	}
	public mdhim_bgetrm_t(Pointer pointer) {
		super(pointer);
	}
}
