package mdhim;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * mdhim data <br>
 * Contains client communicator<br>
 * Contains a list of range servers<br>
 * Contains a pointer to mdhim_rs_t if rank is a range server<br>
 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1551</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public abstract class mdhim_t extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : MPI_Comm (failed to convert type to Java (undefined type)) */
	/** Conversion Error : MPI_Comm (failed to convert type to Java (undefined type)) */
	@Field(2) 
	public int mdhim_rank() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public mdhim_t mdhim_rank(int mdhim_rank) {
		this.io.setIntField(this, 2, mdhim_rank);
		return this;
	}
	@Field(3) 
	public int mdhim_comm_size() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public mdhim_t mdhim_comm_size(int mdhim_comm_size) {
		this.io.setIntField(this, 3, mdhim_comm_size);
		return this;
	}
	@Field(4) 
	public int shutdown() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public mdhim_t shutdown(int shutdown) {
		this.io.setIntField(this, 4, shutdown);
		return this;
	}
	/** C type : index_t* */
	@Field(5) 
	public Pointer<index_t > primary_index() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : index_t* */
	@Field(5) 
	public mdhim_t primary_index(Pointer<index_t > primary_index) {
		this.io.setPointerField(this, 5, primary_index);
		return this;
	}
	/** C type : index_t* */
	@Field(6) 
	public Pointer<index_t > indexes() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : index_t* */
	@Field(6) 
	public mdhim_t indexes(Pointer<index_t > indexes) {
		this.io.setPointerField(this, 6, indexes);
		return this;
	}
	/**
	 * Failed to convert value indexes_lock of type pthread_rwlock_t*<br>
	 * C type : pthread_rwlock_t*
	 */
	/** C type : mdhim_rs_t* */
	@Field(8) 
	public Pointer<mdhim_rs_t > mdhim_rs() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : mdhim_rs_t* */
	@Field(8) 
	public mdhim_t mdhim_rs(Pointer<mdhim_rs_t > mdhim_rs) {
		this.io.setPointerField(this, 8, mdhim_rs);
		return this;
	}
	/**
	 * Failed to convert value receive_msg_mutex of type pthread_mutex_t*<br>
	 * C type : pthread_mutex_t*
	 */
	/**
	 * Failed to convert value receive_msg_ready_cv of type pthread_cond_t*<br>
	 * C type : pthread_cond_t*
	 */
	/** C type : void* */
	@Field(11) 
	public Pointer<? > receive_msg() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : void* */
	@Field(11) 
	public mdhim_t receive_msg(Pointer<? > receive_msg) {
		this.io.setPointerField(this, 11, receive_msg);
		return this;
	}
	/** C type : mdhim_options_t* */
	@Field(12) 
	public Pointer<mdhim_options_t > db_opts() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : mdhim_options_t* */
	@Field(12) 
	public mdhim_t db_opts(Pointer<mdhim_options_t > db_opts) {
		this.io.setPointerField(this, 12, db_opts);
		return this;
	}
}
