package mdhim;
import mdhim.MdhimLibrary.mdhim_store_batch_put_fn_t;
import mdhim.MdhimLibrary.mdhim_store_close_fn_t;
import mdhim.MdhimLibrary.mdhim_store_commit_fn_t;
import mdhim.MdhimLibrary.mdhim_store_del_fn_t;
import mdhim.MdhimLibrary.mdhim_store_get_fn_t;
import mdhim.MdhimLibrary.mdhim_store_get_next_fn_t;
import mdhim.MdhimLibrary.mdhim_store_get_prev_fn_t;
import mdhim.MdhimLibrary.mdhim_store_open_fn_t;
import mdhim.MdhimLibrary.mdhim_store_put_fn_t;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Generic mdhim storage object<br>
 * <i>native declaration : mdhim-tng-ycsb/src/data_store.h:1044</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public class mdhim_store_t extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int type() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public mdhim_store_t type(int type) {
		this.io.setIntField(this, 0, type);
		return this;
	}
	/** C type : void* */
	@Field(1) 
	public Pointer<? > db_handle() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : void* */
	@Field(1) 
	public mdhim_store_t db_handle(Pointer<? > db_handle) {
		this.io.setPointerField(this, 1, db_handle);
		return this;
	}
	/** C type : void* */
	@Field(2) 
	public Pointer<? > db_stats() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : void* */
	@Field(2) 
	public mdhim_store_t db_stats(Pointer<? > db_stats) {
		this.io.setPointerField(this, 2, db_stats);
		return this;
	}
	/** C type : mdhim_store_open_fn_t */
	@Field(3) 
	public Pointer<mdhim_store_open_fn_t > open() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : mdhim_store_open_fn_t */
	@Field(3) 
	public mdhim_store_t open(Pointer<mdhim_store_open_fn_t > open) {
		this.io.setPointerField(this, 3, open);
		return this;
	}
	/** C type : mdhim_store_put_fn_t */
	@Field(4) 
	public Pointer<mdhim_store_put_fn_t > put() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : mdhim_store_put_fn_t */
	@Field(4) 
	public mdhim_store_t put(Pointer<mdhim_store_put_fn_t > put) {
		this.io.setPointerField(this, 4, put);
		return this;
	}
	/** C type : mdhim_store_batch_put_fn_t */
	@Field(5) 
	public Pointer<mdhim_store_batch_put_fn_t > batch_put() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : mdhim_store_batch_put_fn_t */
	@Field(5) 
	public mdhim_store_t batch_put(Pointer<mdhim_store_batch_put_fn_t > batch_put) {
		this.io.setPointerField(this, 5, batch_put);
		return this;
	}
	/** C type : mdhim_store_get_fn_t */
	@Field(6) 
	public Pointer<mdhim_store_get_fn_t > get() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : mdhim_store_get_fn_t */
	@Field(6) 
	public mdhim_store_t get(Pointer<mdhim_store_get_fn_t > get) {
		this.io.setPointerField(this, 6, get);
		return this;
	}
	/** C type : mdhim_store_get_next_fn_t */
	@Field(7) 
	public Pointer<mdhim_store_get_next_fn_t > get_next() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : mdhim_store_get_next_fn_t */
	@Field(7) 
	public mdhim_store_t get_next(Pointer<mdhim_store_get_next_fn_t > get_next) {
		this.io.setPointerField(this, 7, get_next);
		return this;
	}
	/** C type : mdhim_store_get_prev_fn_t */
	@Field(8) 
	public Pointer<mdhim_store_get_prev_fn_t > get_prev() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : mdhim_store_get_prev_fn_t */
	@Field(8) 
	public mdhim_store_t get_prev(Pointer<mdhim_store_get_prev_fn_t > get_prev) {
		this.io.setPointerField(this, 8, get_prev);
		return this;
	}
	/** C type : mdhim_store_del_fn_t */
	@Field(9) 
	public Pointer<mdhim_store_del_fn_t > del() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : mdhim_store_del_fn_t */
	@Field(9) 
	public mdhim_store_t del(Pointer<mdhim_store_del_fn_t > del) {
		this.io.setPointerField(this, 9, del);
		return this;
	}
	/** C type : mdhim_store_commit_fn_t */
	@Field(10) 
	public Pointer<mdhim_store_commit_fn_t > commit() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : mdhim_store_commit_fn_t */
	@Field(10) 
	public mdhim_store_t commit(Pointer<mdhim_store_commit_fn_t > commit) {
		this.io.setPointerField(this, 10, commit);
		return this;
	}
	/** C type : mdhim_store_close_fn_t */
	@Field(11) 
	public Pointer<mdhim_store_close_fn_t > close() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : mdhim_store_close_fn_t */
	@Field(11) 
	public mdhim_store_t close(Pointer<mdhim_store_close_fn_t > close) {
		this.io.setPointerField(this, 11, close);
		return this;
	}
	/** C type : char* */
	@Field(12) 
	public Pointer<Byte > db_user() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : char* */
	@Field(12) 
	public mdhim_store_t db_user(Pointer<Byte > db_user) {
		this.io.setPointerField(this, 12, db_user);
		return this;
	}
	/** C type : char* */
	@Field(13) 
	public Pointer<Byte > db_upswd() {
		return this.io.getPointerField(this, 13);
	}
	/** C type : char* */
	@Field(13) 
	public mdhim_store_t db_upswd(Pointer<Byte > db_upswd) {
		this.io.setPointerField(this, 13, db_upswd);
		return this;
	}
	/** C type : char* */
	@Field(14) 
	public Pointer<Byte > dbs_user() {
		return this.io.getPointerField(this, 14);
	}
	/** C type : char* */
	@Field(14) 
	public mdhim_store_t dbs_user(Pointer<Byte > dbs_user) {
		this.io.setPointerField(this, 14, dbs_user);
		return this;
	}
	/** C type : char* */
	@Field(15) 
	public Pointer<Byte > dbs_upswd() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : char* */
	@Field(15) 
	public mdhim_store_t dbs_upswd(Pointer<Byte > dbs_upswd) {
		this.io.setPointerField(this, 15, dbs_upswd);
		return this;
	}
	/** C type : mdhim_stat* */
	@Field(16) 
	public Pointer<mdhim_stat > mdhim_store_stats() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : mdhim_stat* */
	@Field(16) 
	public mdhim_store_t mdhim_store_stats(Pointer<mdhim_stat > mdhim_store_stats) {
		this.io.setPointerField(this, 16, mdhim_store_stats);
		return this;
	}
	/**
	 * Failed to convert value mdhim_store_stats_lock of type pthread_rwlock_t*<br>
	 * C type : pthread_rwlock_t*
	 */
	public mdhim_store_t() {
		super();
	}
	public mdhim_store_t(Pointer pointer) {
		super(pointer);
	}
}
