package mdhim;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Range server info message<br>
 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1134</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public class mdhim_rsi_t extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int rangesrv_num() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public mdhim_rsi_t rangesrv_num(int rangesrv_num) {
		this.io.setIntField(this, 0, rangesrv_num);
		return this;
	}
	public mdhim_rsi_t() {
		super();
	}
	public mdhim_rsi_t(Pointer pointer) {
		super(pointer);
	}
}
