package mdhim;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1240</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public class mdhim_options_t extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : char* */
	@Field(0) 
	public Pointer<Byte > db_path() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : char* */
	@Field(0) 
	public mdhim_options_t db_path(Pointer<Byte > db_path) {
		this.io.setPointerField(this, 0, db_path);
		return this;
	}
	/** C type : char** */
	@Field(1) 
	public Pointer<Pointer<Byte > > db_paths() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : char** */
	@Field(1) 
	public mdhim_options_t db_paths(Pointer<Pointer<Byte > > db_paths) {
		this.io.setPointerField(this, 1, db_paths);
		return this;
	}
	@Field(2) 
	public int num_paths() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public mdhim_options_t num_paths(int num_paths) {
		this.io.setIntField(this, 2, num_paths);
		return this;
	}
	/** C type : char* */
	@Field(3) 
	public Pointer<Byte > manifest_path() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : char* */
	@Field(3) 
	public mdhim_options_t manifest_path(Pointer<Byte > manifest_path) {
		this.io.setPointerField(this, 3, manifest_path);
		return this;
	}
	/** C type : char* */
	@Field(4) 
	public Pointer<Byte > db_name() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : char* */
	@Field(4) 
	public mdhim_options_t db_name(Pointer<Byte > db_name) {
		this.io.setPointerField(this, 4, db_name);
		return this;
	}
	@Field(5) 
	public int db_type() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public mdhim_options_t db_type(int db_type) {
		this.io.setIntField(this, 5, db_type);
		return this;
	}
	@Field(6) 
	public int db_key_type() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public mdhim_options_t db_key_type(int db_key_type) {
		this.io.setIntField(this, 6, db_key_type);
		return this;
	}
	@Field(7) 
	public int db_create_new() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public mdhim_options_t db_create_new(int db_create_new) {
		this.io.setIntField(this, 7, db_create_new);
		return this;
	}
	@Field(8) 
	public int db_value_append() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public mdhim_options_t db_value_append(int db_value_append) {
		this.io.setIntField(this, 8, db_value_append);
		return this;
	}
	@Field(9) 
	public int debug_level() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public mdhim_options_t debug_level(int debug_level) {
		this.io.setIntField(this, 9, debug_level);
		return this;
	}
	@Field(10) 
	public int rserver_factor() {
		return this.io.getIntField(this, 10);
	}
	@Field(10) 
	public mdhim_options_t rserver_factor(int rserver_factor) {
		this.io.setIntField(this, 10, rserver_factor);
		return this;
	}
	@Field(11) 
	public long max_recs_per_slice() {
		return this.io.getLongField(this, 11);
	}
	@Field(11) 
	public mdhim_options_t max_recs_per_slice(long max_recs_per_slice) {
		this.io.setLongField(this, 11, max_recs_per_slice);
		return this;
	}
	@Field(12) 
	public int num_wthreads() {
		return this.io.getIntField(this, 12);
	}
	@Field(12) 
	public mdhim_options_t num_wthreads(int num_wthreads) {
		this.io.setIntField(this, 12, num_wthreads);
		return this;
	}
	/** C type : char* */
	@Field(13) 
	public Pointer<Byte > db_host() {
		return this.io.getPointerField(this, 13);
	}
	/** C type : char* */
	@Field(13) 
	public mdhim_options_t db_host(Pointer<Byte > db_host) {
		this.io.setPointerField(this, 13, db_host);
		return this;
	}
	/** C type : char* */
	@Field(14) 
	public Pointer<Byte > db_user() {
		return this.io.getPointerField(this, 14);
	}
	/** C type : char* */
	@Field(14) 
	public mdhim_options_t db_user(Pointer<Byte > db_user) {
		this.io.setPointerField(this, 14, db_user);
		return this;
	}
	/** C type : char* */
	@Field(15) 
	public Pointer<Byte > db_upswd() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : char* */
	@Field(15) 
	public mdhim_options_t db_upswd(Pointer<Byte > db_upswd) {
		this.io.setPointerField(this, 15, db_upswd);
		return this;
	}
	/** C type : char* */
	@Field(16) 
	public Pointer<Byte > dbs_user() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : char* */
	@Field(16) 
	public mdhim_options_t dbs_user(Pointer<Byte > dbs_user) {
		this.io.setPointerField(this, 16, dbs_user);
		return this;
	}
	/** C type : char* */
	@Field(17) 
	public Pointer<Byte > dbs_upswd() {
		return this.io.getPointerField(this, 17);
	}
	/** C type : char* */
	@Field(17) 
	public mdhim_options_t dbs_upswd(Pointer<Byte > dbs_upswd) {
		this.io.setPointerField(this, 17, dbs_upswd);
		return this;
	}
	public mdhim_options_t() {
		super();
	}
	public mdhim_options_t(Pointer pointer) {
		super(pointer);
	}
}
