package mdhim;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Ptr;
import org.bridj.ann.Runtime;
import org.bridj.util.DefaultParameterizedType;
/**
 * Wrapper for library <b>mdhim</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
@Runtime(CRuntime.class) 
public class MdhimLibrary {
	static {
		BridJ.register();
	}
	/** <i>native declaration : mdhim-tng-ycsb/src/partitioner.h</i> */
	public static final int MDHIM_DOUBLE_KEY = (int)4;
	/** <i>native declaration : mdhim-tng-ycsb/src/partitioner.h</i> */
	public static final int MAX_KEY_LEN = (int)1048576;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int RANGESRV_WORK_MSG = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_MAX_MSG_SIZE = (int)2147483647;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h</i> */
	public static final int MDHIM_RDWR = (int)3;
	/** <i>native declaration : mdhim-tng-ycsb/src/partitioner.h</i> */
	public static final int MDHIM_STRING_KEY = (int)5;
	/** <i>native declaration : mdhim-tng-ycsb/src/indexes.h</i> */
	public static final int REMOTE_INDEX = (int)4;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_BULK_PUT = (int)2;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int CLIENT_RESPONSE_SIZE_MSG = (int)5;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_GET_PRIMARY_EQ = (int)5;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_BULK_DEL = (int)5;
	/** <i>native declaration : mdhim-tng-ycsb/src/partitioner.h</i> */
	public static final int MDHIM_MAX_SLICES = (int)2147483647;
	/** <i>native declaration : mdhim-tng-ycsb/src/partitioner.h</i> */
	public static final int MDHIM_ALPHABET_EXPONENT = (int)6;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_PUT = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/indexes.h</i> */
	public static final int PRIMARY_INDEX = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h</i> */
	public static final int MDHIM_MIN_STAT = (int)2;
	/** <i>native declaration : mdhim-tng-ycsb/src/partitioner.h</i> */
	public static final int MDHIM_BYTE_KEY = (int)6;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_GET_EQ = (int)0;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h</i> */
	public static final int MDHIM_MAX_STAT = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/partitioner.h</i> */
	public static final int MDHIM_INT_KEY = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h</i> */
	public static final int MDHIM_CREATE = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/mdhim.h</i> */
	public static final int MDHIM_ERROR = (int)-1;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_RECV = (int)7;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_RECV_BULK_GET = (int)9;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MAX_BULK_OPS = (int)1000000;
	/** <i>native declaration : mdhim-tng-ycsb/src/indexes.h</i> */
	public static final int LOCAL_INDEX = (int)3;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_GET_PREV = (int)2;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_GET_NEXT = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/partitioner.h</i> */
	public static final int MDHIM_FLOAT_KEY = (int)3;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_RECV_GET = (int)8;
	/** <i>native declaration : mdhim-tng-ycsb/src/indexes.h</i> */
	public static final int SECONDARY_INDEX = (int)2;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int CLIENT_RESPONSE_MSG = (int)4;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_GET_LAST = (int)4;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int RANGESRV_INFO = (int)3;
	/** <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h</i> */
	public static final int MDHIM_DB_APPEND = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_COMMIT = (int)10;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_DEL = (int)4;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h</i> */
	public static final int LEVELDB = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h</i> */
	public static final int MDHIM_NUM_STAT = (int)3;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h</i> */
	public static final int MYSQLDB = (int)3;
	/** <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h</i> */
	public static final int MDHIM_DB_OVERWRITE = (int)0;
	/** <i>native declaration : mdhim-tng-ycsb/src/mdhim.h</i> */
	public static final int SECONDARY_GLOBAL_INFO = (int)1;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int RANGESRV_WORK_SIZE_MSG = (int)2;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_BULK_GET = (int)3;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h</i> */
	public static final int ROCKSDB = (int)4;
	/** <i>native declaration : mdhim-tng-ycsb/src/mdhim.h</i> */
	public static final int SECONDARY_LOCAL_INFO = (int)2;
	/** <i>native declaration : mdhim-tng-ycsb/src/partitioner.h</i> */
	public static final int MDHIM_LONG_INT_KEY = (int)2;
	/** <i>native declaration : mdhim-tng-ycsb/src/mdhim.h</i> */
	public static final int MDHIM_SUCCESS = (int)0;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_GET_FIRST = (int)3;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h</i> */
	public static final int MDHIM_RDONLY = (int)2;
	/** <i>native declaration : mdhim-tng-ycsb/src/messages.h</i> */
	public static final int MDHIM_CLOSE = (int)6;
	/** <i>native declaration : mdhim-tng-ycsb/src/mdhim.h</i> */
	public static final int MDHIM_DB_ERROR = (int)-2;
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h:977</i> */
	public static abstract class mdhim_store_open_fn_t extends Callback<mdhim_store_open_fn_t > {
		public int apply(Pointer<Pointer<? > > db_handle, Pointer<Pointer<? > > db_stats, Pointer<Byte > path, int flags, int key_type) {
			return apply(Pointer.getPeer(db_handle), Pointer.getPeer(db_stats), Pointer.getPeer(path), flags, key_type);
		}
		public int apply(@Ptr long db_handle, @Ptr long db_stats, @Ptr long path, int flags, int key_type) {
			return apply((Pointer)Pointer.pointerToAddress(db_handle, DefaultParameterizedType.paramType(Pointer.class, null)), (Pointer)Pointer.pointerToAddress(db_stats, DefaultParameterizedType.paramType(Pointer.class, null)), (Pointer)Pointer.pointerToAddress(path, Byte.class), flags, key_type);
		}
	};
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h:978</i> */
	public static abstract class mdhim_store_put_fn_t extends Callback<mdhim_store_put_fn_t > {
		public int apply(Pointer<? > db_handle, Pointer<? > key, int key_len, Pointer<? > data, int data_len) {
			return apply(Pointer.getPeer(db_handle), Pointer.getPeer(key), key_len, Pointer.getPeer(data), data_len);
		}
		public int apply(@Ptr long db_handle, @Ptr long key, int key_len, @Ptr long data, int data_len) {
			return apply(Pointer.pointerToAddress(db_handle), Pointer.pointerToAddress(key), key_len, Pointer.pointerToAddress(data), data_len);
		}
	};
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h:979</i> */
	public static abstract class mdhim_store_batch_put_fn_t extends Callback<mdhim_store_batch_put_fn_t > {
		public int apply(Pointer<? > db_handle, Pointer<Pointer<? > > keys, Pointer<Integer > key_lens, Pointer<Pointer<? > > data, Pointer<Integer > data_lens, int num_records) {
			return apply(Pointer.getPeer(db_handle), Pointer.getPeer(keys), Pointer.getPeer(key_lens), Pointer.getPeer(data), Pointer.getPeer(data_lens), num_records);
		}
		public int apply(@Ptr long db_handle, @Ptr long keys, @Ptr long key_lens, @Ptr long data, @Ptr long data_lens, int num_records) {
			return apply(Pointer.pointerToAddress(db_handle), (Pointer)Pointer.pointerToAddress(keys, DefaultParameterizedType.paramType(Pointer.class, null)), (Pointer)Pointer.pointerToAddress(key_lens, Integer.class), (Pointer)Pointer.pointerToAddress(data, DefaultParameterizedType.paramType(Pointer.class, null)), (Pointer)Pointer.pointerToAddress(data_lens, Integer.class), num_records);
		}
	};
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h:980</i> */
	public static abstract class mdhim_store_get_fn_t extends Callback<mdhim_store_get_fn_t > {
		public int apply(Pointer<? > db_handle, Pointer<? > key, int key_len, Pointer<Pointer<? > > data, Pointer<Integer > data_len) {
			return apply(Pointer.getPeer(db_handle), Pointer.getPeer(key), key_len, Pointer.getPeer(data), Pointer.getPeer(data_len));
		}
		public int apply(@Ptr long db_handle, @Ptr long key, int key_len, @Ptr long data, @Ptr long data_len) {
			return apply(Pointer.pointerToAddress(db_handle), Pointer.pointerToAddress(key), key_len, (Pointer)Pointer.pointerToAddress(data, DefaultParameterizedType.paramType(Pointer.class, null)), (Pointer)Pointer.pointerToAddress(data_len, Integer.class));
		}
	};
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h:981</i> */
	public static abstract class mdhim_store_get_next_fn_t extends Callback<mdhim_store_get_next_fn_t > {
		public int apply(Pointer<? > db_handle, Pointer<Pointer<? > > key, Pointer<Integer > key_len, Pointer<Pointer<? > > data, Pointer<Integer > data_len) {
			return apply(Pointer.getPeer(db_handle), Pointer.getPeer(key), Pointer.getPeer(key_len), Pointer.getPeer(data), Pointer.getPeer(data_len));
		}
		public int apply(@Ptr long db_handle, @Ptr long key, @Ptr long key_len, @Ptr long data, @Ptr long data_len) {
			return apply(Pointer.pointerToAddress(db_handle), (Pointer)Pointer.pointerToAddress(key, DefaultParameterizedType.paramType(Pointer.class, null)), (Pointer)Pointer.pointerToAddress(key_len, Integer.class), (Pointer)Pointer.pointerToAddress(data, DefaultParameterizedType.paramType(Pointer.class, null)), (Pointer)Pointer.pointerToAddress(data_len, Integer.class));
		}
	};
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h:982</i> */
	public static abstract class mdhim_store_get_prev_fn_t extends Callback<mdhim_store_get_prev_fn_t > {
		public int apply(Pointer<? > db_handle, Pointer<Pointer<? > > key, Pointer<Integer > key_len, Pointer<Pointer<? > > data, Pointer<Integer > data_len) {
			return apply(Pointer.getPeer(db_handle), Pointer.getPeer(key), Pointer.getPeer(key_len), Pointer.getPeer(data), Pointer.getPeer(data_len));
		}
		public int apply(@Ptr long db_handle, @Ptr long key, @Ptr long key_len, @Ptr long data, @Ptr long data_len) {
			return apply(Pointer.pointerToAddress(db_handle), (Pointer)Pointer.pointerToAddress(key, DefaultParameterizedType.paramType(Pointer.class, null)), (Pointer)Pointer.pointerToAddress(key_len, Integer.class), (Pointer)Pointer.pointerToAddress(data, DefaultParameterizedType.paramType(Pointer.class, null)), (Pointer)Pointer.pointerToAddress(data_len, Integer.class));
		}
	};
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h:983</i> */
	public static abstract class mdhim_store_del_fn_t extends Callback<mdhim_store_del_fn_t > {
		public int apply(Pointer<? > db_handle, Pointer<? > key, int key_len) {
			return apply(Pointer.getPeer(db_handle), Pointer.getPeer(key), key_len);
		}
		public int apply(@Ptr long db_handle, @Ptr long key, int key_len) {
			return apply(Pointer.pointerToAddress(db_handle), Pointer.pointerToAddress(key), key_len);
		}
	};
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h:984</i> */
	public static abstract class mdhim_store_commit_fn_t extends Callback<mdhim_store_commit_fn_t > {
		public int apply(Pointer<? > db_handle) {
			return apply(Pointer.getPeer(db_handle));
		}
		public int apply(@Ptr long db_handle) {
			return apply(Pointer.pointerToAddress(db_handle));
		}
	};
	/** <i>native declaration : mdhim-tng-ycsb/src/data_store.h:985</i> */
	public static abstract class mdhim_store_close_fn_t extends Callback<mdhim_store_close_fn_t > {
		public int apply(Pointer<? > db_handle, Pointer<? > db_stats) {
			return apply(Pointer.getPeer(db_handle), Pointer.getPeer(db_stats));
		}
		public int apply(@Ptr long db_handle, @Ptr long db_stats) {
			return apply(Pointer.pointerToAddress(db_handle), Pointer.pointerToAddress(db_stats));
		}
	};
	/**
	 * Initializes the data store based on the type given (i.e., LEVELDB, etc...)<br>
	 * Original signature : <code>mdhim_store_t* mdhim_db_init(int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/data_store.h:1049</i>
	 */
	public static Pointer<mdhim_store_t > mdhim_db_init(int db_type) {
		return (Pointer)Pointer.pointerToAddress(mdhim_db_init$2(db_type), mdhim_store_t.class);
	}
	@Ptr 
	@Name("mdhim_db_init") 
	protected native static long mdhim_db_init$2(int db_type);
	/**
	 * Original signature : <code>int send_rangesrv_work(mdhim_t*, int, void*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1171</i>
	 */
	public static int send_rangesrv_work(Pointer<mdhim_t > md, int dest, Pointer<? > message) {
		return send_rangesrv_work(Pointer.getPeer(md), dest, Pointer.getPeer(message));
	}
	protected native static int send_rangesrv_work(@Ptr long md, int dest, @Ptr long message);
	/**
	 * Original signature : <code>int send_all_rangesrv_work(mdhim_t*, void**, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1173</i>
	 */
	public static int send_all_rangesrv_work(Pointer<mdhim_t > md, Pointer<Pointer<? > > messages, int num_srvs) {
		return send_all_rangesrv_work(Pointer.getPeer(md), Pointer.getPeer(messages), num_srvs);
	}
	protected native static int send_all_rangesrv_work(@Ptr long md, @Ptr long messages, int num_srvs);
	/**
	 * Original signature : <code>int receive_rangesrv_work(mdhim_t*, int*, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1175</i>
	 */
	public static int receive_rangesrv_work(Pointer<mdhim_t > md, Pointer<Integer > src, Pointer<Pointer<? > > message) {
		return receive_rangesrv_work(Pointer.getPeer(md), Pointer.getPeer(src), Pointer.getPeer(message));
	}
	protected native static int receive_rangesrv_work(@Ptr long md, @Ptr long src, @Ptr long message);
	/**
	 * Original signature : <code>int send_client_response(mdhim_t*, int, void*, void**, MPI_Request**, MPI_Request**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1177</i>
	 */
	public static int send_client_response(Pointer<mdhim_t > md, int dest, Pointer<? > message, Pointer<Pointer<? > > sendbuf, Pointer<Pointer<MdhimLibrary.MPI_Request > > size_req, Pointer<Pointer<MdhimLibrary.MPI_Request > > msg_req) {
		return send_client_response(Pointer.getPeer(md), dest, Pointer.getPeer(message), Pointer.getPeer(sendbuf), Pointer.getPeer(size_req), Pointer.getPeer(msg_req));
	}
	protected native static int send_client_response(@Ptr long md, int dest, @Ptr long message, @Ptr long sendbuf, @Ptr long size_req, @Ptr long msg_req);
	/**
	 * Original signature : <code>int receive_client_response(mdhim_t*, int, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1179</i>
	 */
	public static int receive_client_response(Pointer<mdhim_t > md, int src, Pointer<Pointer<? > > message) {
		return receive_client_response(Pointer.getPeer(md), src, Pointer.getPeer(message));
	}
	protected native static int receive_client_response(@Ptr long md, int src, @Ptr long message);
	/**
	 * Original signature : <code>int receive_all_client_responses(mdhim_t*, int*, int, void***)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1181</i>
	 */
	public static int receive_all_client_responses(Pointer<mdhim_t > md, Pointer<Integer > srcs, int nsrcs, Pointer<Pointer<Pointer<? > > > messages) {
		return receive_all_client_responses(Pointer.getPeer(md), Pointer.getPeer(srcs), nsrcs, Pointer.getPeer(messages));
	}
	protected native static int receive_all_client_responses(@Ptr long md, @Ptr long srcs, int nsrcs, @Ptr long messages);
	/**
	 * Original signature : <code>int pack_put_message(mdhim_t*, mdhim_putm_t*, void**, int*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1183</i>
	 */
	public static int pack_put_message(Pointer<mdhim_t > md, Pointer<mdhim_putm_t > pm, Pointer<Pointer<? > > sendbuf, Pointer<Integer > sendsize) {
		return pack_put_message(Pointer.getPeer(md), Pointer.getPeer(pm), Pointer.getPeer(sendbuf), Pointer.getPeer(sendsize));
	}
	protected native static int pack_put_message(@Ptr long md, @Ptr long pm, @Ptr long sendbuf, @Ptr long sendsize);
	/**
	 * Original signature : <code>int pack_bput_message(mdhim_t*, mdhim_bputm_t*, void**, int*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1185</i>
	 */
	public static int pack_bput_message(Pointer<mdhim_t > md, Pointer<mdhim_bputm_t > bpm, Pointer<Pointer<? > > sendbuf, Pointer<Integer > sendsize) {
		return pack_bput_message(Pointer.getPeer(md), Pointer.getPeer(bpm), Pointer.getPeer(sendbuf), Pointer.getPeer(sendsize));
	}
	protected native static int pack_bput_message(@Ptr long md, @Ptr long bpm, @Ptr long sendbuf, @Ptr long sendsize);
	/**
	 * Original signature : <code>int unpack_put_message(mdhim_t*, void*, int, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1187</i>
	 */
	public static int unpack_put_message(Pointer<mdhim_t > md, Pointer<? > message, int mesg_size, Pointer<Pointer<? > > pm) {
		return unpack_put_message(Pointer.getPeer(md), Pointer.getPeer(message), mesg_size, Pointer.getPeer(pm));
	}
	protected native static int unpack_put_message(@Ptr long md, @Ptr long message, int mesg_size, @Ptr long pm);
	/**
	 * Original signature : <code>int unpack_bput_message(mdhim_t*, void*, int, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1189</i>
	 */
	public static int unpack_bput_message(Pointer<mdhim_t > md, Pointer<? > message, int mesg_size, Pointer<Pointer<? > > bpm) {
		return unpack_bput_message(Pointer.getPeer(md), Pointer.getPeer(message), mesg_size, Pointer.getPeer(bpm));
	}
	protected native static int unpack_bput_message(@Ptr long md, @Ptr long message, int mesg_size, @Ptr long bpm);
	/**
	 * Original signature : <code>int pack_get_message(mdhim_t*, mdhim_getm_t*, void**, int*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1191</i>
	 */
	public static int pack_get_message(Pointer<mdhim_t > md, Pointer<mdhim_getm_t > gm, Pointer<Pointer<? > > sendbuf, Pointer<Integer > sendsize) {
		return pack_get_message(Pointer.getPeer(md), Pointer.getPeer(gm), Pointer.getPeer(sendbuf), Pointer.getPeer(sendsize));
	}
	protected native static int pack_get_message(@Ptr long md, @Ptr long gm, @Ptr long sendbuf, @Ptr long sendsize);
	/**
	 * Original signature : <code>int pack_bget_message(mdhim_t*, mdhim_bgetm_t*, void**, int*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1193</i>
	 */
	public static int pack_bget_message(Pointer<mdhim_t > md, Pointer<mdhim_bgetm_t > bgm, Pointer<Pointer<? > > sendbuf, Pointer<Integer > sendsize) {
		return pack_bget_message(Pointer.getPeer(md), Pointer.getPeer(bgm), Pointer.getPeer(sendbuf), Pointer.getPeer(sendsize));
	}
	protected native static int pack_bget_message(@Ptr long md, @Ptr long bgm, @Ptr long sendbuf, @Ptr long sendsize);
	/**
	 * Original signature : <code>int unpack_get_message(mdhim_t*, void*, int, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1195</i>
	 */
	public static int unpack_get_message(Pointer<mdhim_t > md, Pointer<? > message, int mesg_size, Pointer<Pointer<? > > gm) {
		return unpack_get_message(Pointer.getPeer(md), Pointer.getPeer(message), mesg_size, Pointer.getPeer(gm));
	}
	protected native static int unpack_get_message(@Ptr long md, @Ptr long message, int mesg_size, @Ptr long gm);
	/**
	 * Original signature : <code>int unpack_bget_message(mdhim_t*, void*, int, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1197</i>
	 */
	public static int unpack_bget_message(Pointer<mdhim_t > md, Pointer<? > message, int mesg_size, Pointer<Pointer<? > > bgm) {
		return unpack_bget_message(Pointer.getPeer(md), Pointer.getPeer(message), mesg_size, Pointer.getPeer(bgm));
	}
	protected native static int unpack_bget_message(@Ptr long md, @Ptr long message, int mesg_size, @Ptr long bgm);
	/**
	 * Original signature : <code>int pack_bgetrm_message(mdhim_t*, mdhim_bgetrm_t*, void**, int*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1199</i>
	 */
	public static int pack_bgetrm_message(Pointer<mdhim_t > md, Pointer<mdhim_bgetrm_t > bgrm, Pointer<Pointer<? > > sendbuf, Pointer<Integer > sendsize) {
		return pack_bgetrm_message(Pointer.getPeer(md), Pointer.getPeer(bgrm), Pointer.getPeer(sendbuf), Pointer.getPeer(sendsize));
	}
	protected native static int pack_bgetrm_message(@Ptr long md, @Ptr long bgrm, @Ptr long sendbuf, @Ptr long sendsize);
	/**
	 * Original signature : <code>int unpack_bgetrm_message(mdhim_t*, void*, int, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1201</i>
	 */
	public static int unpack_bgetrm_message(Pointer<mdhim_t > md, Pointer<? > message, int mesg_size, Pointer<Pointer<? > > bgrm) {
		return unpack_bgetrm_message(Pointer.getPeer(md), Pointer.getPeer(message), mesg_size, Pointer.getPeer(bgrm));
	}
	protected native static int unpack_bgetrm_message(@Ptr long md, @Ptr long message, int mesg_size, @Ptr long bgrm);
	/**
	 * Original signature : <code>int pack_del_message(mdhim_t*, mdhim_delm_t*, void**, int*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1203</i>
	 */
	public static int pack_del_message(Pointer<mdhim_t > md, Pointer<mdhim_delm_t > dm, Pointer<Pointer<? > > sendbuf, Pointer<Integer > sendsize) {
		return pack_del_message(Pointer.getPeer(md), Pointer.getPeer(dm), Pointer.getPeer(sendbuf), Pointer.getPeer(sendsize));
	}
	protected native static int pack_del_message(@Ptr long md, @Ptr long dm, @Ptr long sendbuf, @Ptr long sendsize);
	/**
	 * Original signature : <code>int pack_bdel_message(mdhim_t*, mdhim_bdelm_t*, void**, int*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1205</i>
	 */
	public static int pack_bdel_message(Pointer<mdhim_t > md, Pointer<mdhim_bdelm_t > bdm, Pointer<Pointer<? > > sendbuf, Pointer<Integer > sendsize) {
		return pack_bdel_message(Pointer.getPeer(md), Pointer.getPeer(bdm), Pointer.getPeer(sendbuf), Pointer.getPeer(sendsize));
	}
	protected native static int pack_bdel_message(@Ptr long md, @Ptr long bdm, @Ptr long sendbuf, @Ptr long sendsize);
	/**
	 * Original signature : <code>int unpack_del_message(mdhim_t*, void*, int, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1207</i>
	 */
	public static int unpack_del_message(Pointer<mdhim_t > md, Pointer<? > message, int mesg_size, Pointer<Pointer<? > > dm) {
		return unpack_del_message(Pointer.getPeer(md), Pointer.getPeer(message), mesg_size, Pointer.getPeer(dm));
	}
	protected native static int unpack_del_message(@Ptr long md, @Ptr long message, int mesg_size, @Ptr long dm);
	/**
	 * Original signature : <code>int unpack_bdel_message(mdhim_t*, void*, int, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1209</i>
	 */
	public static int unpack_bdel_message(Pointer<mdhim_t > md, Pointer<? > message, int mesg_size, Pointer<Pointer<? > > bdm) {
		return unpack_bdel_message(Pointer.getPeer(md), Pointer.getPeer(message), mesg_size, Pointer.getPeer(bdm));
	}
	protected native static int unpack_bdel_message(@Ptr long md, @Ptr long message, int mesg_size, @Ptr long bdm);
	/**
	 * Original signature : <code>int pack_return_message(mdhim_t*, mdhim_rm_t*, void**, int*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1211</i>
	 */
	public static int pack_return_message(Pointer<mdhim_t > md, Pointer<mdhim_rm_t > rm, Pointer<Pointer<? > > sendbuf, Pointer<Integer > sendsize) {
		return pack_return_message(Pointer.getPeer(md), Pointer.getPeer(rm), Pointer.getPeer(sendbuf), Pointer.getPeer(sendsize));
	}
	protected native static int pack_return_message(@Ptr long md, @Ptr long rm, @Ptr long sendbuf, @Ptr long sendsize);
	/**
	 * Original signature : <code>int unpack_return_message(mdhim_t*, void*, void**)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1213</i>
	 */
	public static int unpack_return_message(Pointer<mdhim_t > md, Pointer<? > message, Pointer<Pointer<? > > rm) {
		return unpack_return_message(Pointer.getPeer(md), Pointer.getPeer(message), Pointer.getPeer(rm));
	}
	protected native static int unpack_return_message(@Ptr long md, @Ptr long message, @Ptr long rm);
	/**
	 * Original signature : <code>int pack_base_message(mdhim_t*, mdhim_basem_t*, void**, int*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1215</i>
	 */
	public static int pack_base_message(Pointer<mdhim_t > md, Pointer<mdhim_basem_t > cm, Pointer<Pointer<? > > sendbuf, Pointer<Integer > sendsize) {
		return pack_base_message(Pointer.getPeer(md), Pointer.getPeer(cm), Pointer.getPeer(sendbuf), Pointer.getPeer(sendsize));
	}
	protected native static int pack_base_message(@Ptr long md, @Ptr long cm, @Ptr long sendbuf, @Ptr long sendsize);
	/**
	 * Original signature : <code>void mdhim_full_release_msg(void*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1217</i>
	 */
	public static void mdhim_full_release_msg(Pointer<? > message) {
		mdhim_full_release_msg(Pointer.getPeer(message));
	}
	protected native static void mdhim_full_release_msg(@Ptr long message);
	/**
	 * Original signature : <code>void mdhim_partial_release_msg(void*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/messages.h:1219</i>
	 */
	public static void mdhim_partial_release_msg(Pointer<? > message) {
		mdhim_partial_release_msg(Pointer.getPeer(message));
	}
	protected native static void mdhim_partial_release_msg(@Ptr long message);
	/**
	 * Original signature : <code>mdhim_options_t* mdhim_options_init()</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1242</i>
	 */
	public static Pointer<mdhim_options_t > mdhim_options_init() {
		return (Pointer)Pointer.pointerToAddress(mdhim_options_init$2(), mdhim_options_t.class);
	}
	@Ptr 
	@Name("mdhim_options_init") 
	protected native static long mdhim_options_init$2();
	/**
	 * Original signature : <code>void mdhim_options_set_db_path(mdhim_options_t*, char*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1244</i>
	 */
	public static void mdhim_options_set_db_path(Pointer<mdhim_options_t > opts, Pointer<Byte > path) {
		mdhim_options_set_db_path(Pointer.getPeer(opts), Pointer.getPeer(path));
	}
	protected native static void mdhim_options_set_db_path(@Ptr long opts, @Ptr long path);
	/**
	 * Original signature : <code>void mdhim_options_set_db_paths(mdhim_options_t*, char**, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1246</i>
	 */
	public static void mdhim_options_set_db_paths(Pointer<mdhim_options_t > opts, Pointer<Pointer<Byte > > paths, int num_paths) {
		mdhim_options_set_db_paths(Pointer.getPeer(opts), Pointer.getPeer(paths), num_paths);
	}
	protected native static void mdhim_options_set_db_paths(@Ptr long opts, @Ptr long paths, int num_paths);
	/**
	 * Original signature : <code>void mdhim_options_set_db_name(mdhim_options_t*, char*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1248</i>
	 */
	public static void mdhim_options_set_db_name(Pointer<mdhim_options_t > opts, Pointer<Byte > name) {
		mdhim_options_set_db_name(Pointer.getPeer(opts), Pointer.getPeer(name));
	}
	protected native static void mdhim_options_set_db_name(@Ptr long opts, @Ptr long name);
	/**
	 * Original signature : <code>void mdhim_options_set_db_type(mdhim_options_t*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1250</i>
	 */
	public static void mdhim_options_set_db_type(Pointer<mdhim_options_t > opts, int type) {
		mdhim_options_set_db_type(Pointer.getPeer(opts), type);
	}
	protected native static void mdhim_options_set_db_type(@Ptr long opts, int type);
	/**
	 * Original signature : <code>void mdhim_options_set_key_type(mdhim_options_t*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1252</i>
	 */
	public static void mdhim_options_set_key_type(Pointer<mdhim_options_t > opts, int key_type) {
		mdhim_options_set_key_type(Pointer.getPeer(opts), key_type);
	}
	protected native static void mdhim_options_set_key_type(@Ptr long opts, int key_type);
	/**
	 * Original signature : <code>void mdhim_options_set_create_new_db(mdhim_options_t*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1254</i>
	 */
	public static void mdhim_options_set_create_new_db(Pointer<mdhim_options_t > opts, int create_new) {
		mdhim_options_set_create_new_db(Pointer.getPeer(opts), create_new);
	}
	protected native static void mdhim_options_set_create_new_db(@Ptr long opts, int create_new);
	/**
	 * Original signature : <code>void mdhim_options_set_login_c(mdhim_options_t*, char*, char*, char*, char*, char*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1256</i>
	 */
	public static void mdhim_options_set_login_c(Pointer<mdhim_options_t > opts, Pointer<Byte > db_hl, Pointer<Byte > db_ln, Pointer<Byte > db_pw, Pointer<Byte > dbs_ln, Pointer<Byte > dbs_pw) {
		mdhim_options_set_login_c(Pointer.getPeer(opts), Pointer.getPeer(db_hl), Pointer.getPeer(db_ln), Pointer.getPeer(db_pw), Pointer.getPeer(dbs_ln), Pointer.getPeer(dbs_pw));
	}
	protected native static void mdhim_options_set_login_c(@Ptr long opts, @Ptr long db_hl, @Ptr long db_ln, @Ptr long db_pw, @Ptr long dbs_ln, @Ptr long dbs_pw);
	/**
	 * Original signature : <code>void mdhim_options_set_debug_level(mdhim_options_t*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1258</i>
	 */
	public static void mdhim_options_set_debug_level(Pointer<mdhim_options_t > opts, int dbug) {
		mdhim_options_set_debug_level(Pointer.getPeer(opts), dbug);
	}
	protected native static void mdhim_options_set_debug_level(@Ptr long opts, int dbug);
	/**
	 * Original signature : <code>void mdhim_options_set_value_append(mdhim_options_t*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1260</i>
	 */
	public static void mdhim_options_set_value_append(Pointer<mdhim_options_t > opts, int append) {
		mdhim_options_set_value_append(Pointer.getPeer(opts), append);
	}
	protected native static void mdhim_options_set_value_append(@Ptr long opts, int append);
	/**
	 * Original signature : <code>void mdhim_options_set_server_factor(mdhim_options_t*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1262</i>
	 */
	public static void mdhim_options_set_server_factor(Pointer<mdhim_options_t > opts, int server_factor) {
		mdhim_options_set_server_factor(Pointer.getPeer(opts), server_factor);
	}
	protected native static void mdhim_options_set_server_factor(@Ptr long opts, int server_factor);
	/**
	 * Original signature : <code>void mdhim_options_set_max_recs_per_slice(mdhim_options_t*, uint64_t)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1264</i>
	 */
	public static void mdhim_options_set_max_recs_per_slice(Pointer<mdhim_options_t > opts, long max_recs_per_slice) {
		mdhim_options_set_max_recs_per_slice(Pointer.getPeer(opts), max_recs_per_slice);
	}
	protected native static void mdhim_options_set_max_recs_per_slice(@Ptr long opts, long max_recs_per_slice);
	/**
	 * Original signature : <code>void mdhim_options_set_num_worker_threads(mdhim_options_t*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1266</i>
	 */
	public static void mdhim_options_set_num_worker_threads(Pointer<mdhim_options_t > opts, int num_wthreads) {
		mdhim_options_set_num_worker_threads(Pointer.getPeer(opts), num_wthreads);
	}
	protected native static void mdhim_options_set_num_worker_threads(@Ptr long opts, int num_wthreads);
	/**
	 * Original signature : <code>void mdhim_options_destroy(mdhim_options_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_options.h:1268</i>
	 */
	public static void mdhim_options_destroy(Pointer<mdhim_options_t > opts) {
		mdhim_options_destroy(Pointer.getPeer(opts));
	}
	protected native static void mdhim_options_destroy(@Ptr long opts);
	/**
	 * Original signature : <code>int update_all_stats(mdhim_t*, index_t*, void*, uint32_t)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1322</i>
	 */
	public static int update_all_stats(Pointer<mdhim_t > md, Pointer<index_t > bi, Pointer<? > key, int key_len) {
		return update_all_stats(Pointer.getPeer(md), Pointer.getPeer(bi), Pointer.getPeer(key), key_len);
	}
	protected native static int update_all_stats(@Ptr long md, @Ptr long bi, @Ptr long key, int key_len);
	/**
	 * Original signature : <code>int load_stats(mdhim_t*, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1324</i>
	 */
	public static int load_stats(Pointer<mdhim_t > md, Pointer<index_t > bi) {
		return load_stats(Pointer.getPeer(md), Pointer.getPeer(bi));
	}
	protected native static int load_stats(@Ptr long md, @Ptr long bi);
	/**
	 * Original signature : <code>int write_stats(mdhim_t*, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1326</i>
	 */
	public static int write_stats(Pointer<mdhim_t > md, Pointer<index_t > bi) {
		return write_stats(Pointer.getPeer(md), Pointer.getPeer(bi));
	}
	protected native static int write_stats(@Ptr long md, @Ptr long bi);
	/**
	 * Original signature : <code>int open_db_store(mdhim_t*, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1328</i>
	 */
	public static int open_db_store(Pointer<mdhim_t > md, Pointer<index_t > index) {
		return open_db_store(Pointer.getPeer(md), Pointer.getPeer(index));
	}
	protected native static int open_db_store(@Ptr long md, @Ptr long index);
	/**
	 * Original signature : <code>uint32_t get_num_range_servers(mdhim_t*, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1330</i>
	 */
	public static int get_num_range_servers(Pointer<mdhim_t > md, Pointer<index_t > index) {
		return get_num_range_servers(Pointer.getPeer(md), Pointer.getPeer(index));
	}
	protected native static int get_num_range_servers(@Ptr long md, @Ptr long index);
	/**
	 * Original signature : <code>index_t* create_local_index(mdhim_t*, int, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1332</i>
	 */
	public static Pointer<index_t > create_local_index(Pointer<mdhim_t > md, int db_type, int key_type) {
		return (Pointer)Pointer.pointerToAddress(create_local_index(Pointer.getPeer(md), db_type, key_type), index_t.class);
	}
	@Ptr 
	protected native static long create_local_index(@Ptr long md, int db_type, int key_type);
	/**
	 * Original signature : <code>index_t* create_global_index(mdhim_t*, int, int, int, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1334</i>
	 */
	public static Pointer<index_t > create_global_index(Pointer<mdhim_t > md, int server_factor, int max_recs_per_slice, int db_type, int key_type) {
		return (Pointer)Pointer.pointerToAddress(create_global_index(Pointer.getPeer(md), server_factor, max_recs_per_slice, db_type, key_type), index_t.class);
	}
	@Ptr 
	protected native static long create_global_index(@Ptr long md, int server_factor, int max_recs_per_slice, int db_type, int key_type);
	/**
	 * Original signature : <code>int get_rangesrvs(mdhim_t*, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1336</i>
	 */
	public static int get_rangesrvs(Pointer<mdhim_t > md, Pointer<index_t > index) {
		return get_rangesrvs(Pointer.getPeer(md), Pointer.getPeer(index));
	}
	protected native static int get_rangesrvs(@Ptr long md, @Ptr long index);
	/**
	 * Original signature : <code>uint32_t is_range_server(mdhim_t*, int, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1338</i>
	 */
	public static int is_range_server(Pointer<mdhim_t > md, int rank, Pointer<index_t > index) {
		return is_range_server(Pointer.getPeer(md), rank, Pointer.getPeer(index));
	}
	protected native static int is_range_server(@Ptr long md, int rank, @Ptr long index);
	/**
	 * Original signature : <code>int index_init_comm(mdhim_t*, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1340</i>
	 */
	public static int index_init_comm(Pointer<mdhim_t > md, Pointer<index_t > bi) {
		return index_init_comm(Pointer.getPeer(md), Pointer.getPeer(bi));
	}
	protected native static int index_init_comm(@Ptr long md, @Ptr long bi);
	/**
	 * Original signature : <code>int get_stat_flush(mdhim_t*, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1342</i>
	 */
	public static int get_stat_flush(Pointer<mdhim_t > md, Pointer<index_t > index) {
		return get_stat_flush(Pointer.getPeer(md), Pointer.getPeer(index));
	}
	protected native static int get_stat_flush(@Ptr long md, @Ptr long index);
	/**
	 * Original signature : <code>index_t* get_index(mdhim_t*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1344</i>
	 */
	public static Pointer<index_t > get_index(Pointer<mdhim_t > md, int index_id) {
		return (Pointer)Pointer.pointerToAddress(get_index(Pointer.getPeer(md), index_id), index_t.class);
	}
	@Ptr 
	protected native static long get_index(@Ptr long md, int index_id);
	/**
	 * Original signature : <code>void indexes_release(mdhim_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1346</i>
	 */
	public static void indexes_release(Pointer<mdhim_t > md) {
		indexes_release(Pointer.getPeer(md));
	}
	protected native static void indexes_release(@Ptr long md);
	/**
	 * Original signature : <code>int im_range_server(index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1348</i>
	 */
	public static int im_range_server(Pointer<index_t > index) {
		return im_range_server(Pointer.getPeer(index));
	}
	protected native static int im_range_server(@Ptr long index);
	/**
	 * Original signature : <code>int range_server_add_work(mdhim_t*, work_item*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/range_server.h:1385</i>
	 */
	public static int range_server_add_work(Pointer<mdhim_t > md, Pointer<work_item > item) {
		return range_server_add_work(Pointer.getPeer(md), Pointer.getPeer(item));
	}
	protected native static int range_server_add_work(@Ptr long md, @Ptr long item);
	/**
	 * Original signature : <code>int range_server_init(mdhim_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/range_server.h:1387</i>
	 */
	public static int range_server_init(Pointer<mdhim_t > md) {
		return range_server_init(Pointer.getPeer(md));
	}
	protected native static int range_server_init(@Ptr long md);
	/**
	 * Original signature : <code>int range_server_init_comm(mdhim_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/range_server.h:1389</i>
	 */
	public static int range_server_init_comm(Pointer<mdhim_t > md) {
		return range_server_init_comm(Pointer.getPeer(md));
	}
	protected native static int range_server_init_comm(@Ptr long md);
	/**
	 * Original signature : <code>int range_server_stop(mdhim_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/range_server.h:1391</i>
	 */
	public static int range_server_stop(Pointer<mdhim_t > md) {
		return range_server_stop(Pointer.getPeer(md));
	}
	protected native static int range_server_stop(@Ptr long md);
	/**
	 * Add an outstanding request<br>
	 * Original signature : <code>int range_server_add_oreq(mdhim_t*, MPI_Request*, void*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/range_server.h:1396</i>
	 */
	public static int range_server_add_oreq(Pointer<mdhim_t > md, Pointer<MdhimLibrary.MPI_Request > req, Pointer<? > msg) {
		return range_server_add_oreq(Pointer.getPeer(md), Pointer.getPeer(req), Pointer.getPeer(msg));
	}
	protected native static int range_server_add_oreq(@Ptr long md, @Ptr long req, @Ptr long msg);
	/**
	 * Clean outstanding reqs<br>
	 * Original signature : <code>int range_server_clean_oreqs(mdhim_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/range_server.h:1401</i>
	 */
	public static int range_server_clean_oreqs(Pointer<mdhim_t > md) {
		return range_server_clean_oreqs(Pointer.getPeer(md));
	}
	protected native static int range_server_clean_oreqs(@Ptr long md);
	/**
	 * Original signature : <code>void partitioner_init()</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1415</i>
	 */
	public static native void partitioner_init();
	/**
	 * Original signature : <code>void partitioner_release()</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1417</i>
	 */
	public static native void partitioner_release();
	/**
	 * Original signature : <code>rangesrv_list* get_range_servers(mdhim_t*, index_t*, void*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1419</i>
	 */
	public static Pointer<rangesrv_list > get_range_servers(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<? > key, int key_len) {
		return (Pointer)Pointer.pointerToAddress(get_range_servers(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(key), key_len), rangesrv_list.class);
	}
	@Ptr 
	protected native static long get_range_servers(@Ptr long md, @Ptr long index, @Ptr long key, int key_len);
	/**
	 * Original signature : <code>rangesrv_info* get_range_server_by_slice(mdhim_t*, index_t*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1421</i>
	 */
	public static Pointer<rangesrv_info > get_range_server_by_slice(Pointer<mdhim_t > md, Pointer<index_t > index, int slice) {
		return (Pointer)Pointer.pointerToAddress(get_range_server_by_slice(Pointer.getPeer(md), Pointer.getPeer(index), slice), rangesrv_info.class);
	}
	@Ptr 
	protected native static long get_range_server_by_slice(@Ptr long md, @Ptr long index, int slice);
	/**
	 * Original signature : <code>void build_alphabet()</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1423</i>
	 */
	public static native void build_alphabet();
	/**
	 * Original signature : <code>int verify_key(index_t*, void*, int, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1425</i>
	 */
	public static int verify_key(Pointer<index_t > index, Pointer<? > key, int key_len, int key_type) {
		return verify_key(Pointer.getPeer(index), Pointer.getPeer(key), key_len, key_type);
	}
	protected native static int verify_key(@Ptr long index, @Ptr long key, int key_len, int key_type);
	/**
	 * Original signature : <code>long double get_str_num(void*, uint32_t)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1427</i>
	 */
	public static double get_str_num(Pointer<? > key, int key_len) {
		return get_str_num(Pointer.getPeer(key), key_len);
	}
	protected native static double get_str_num(@Ptr long key, int key_len);
	/**
	 * Original signature : <code>long double get_byte_num(void*, uint32_t)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1429</i>
	 */
	public static double get_byte_num(Pointer<? > key, int key_len) {
		return get_byte_num(Pointer.getPeer(key), key_len);
	}
	protected native static double get_byte_num(@Ptr long key, int key_len);
	/**
	 * Original signature : <code>int get_slice_num(mdhim_t*, index_t*, void*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1431</i>
	 */
	public static int get_slice_num(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<? > key, int key_len) {
		return get_slice_num(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(key), key_len);
	}
	protected native static int get_slice_num(@Ptr long md, @Ptr long index, @Ptr long key, int key_len);
	/**
	 * Original signature : <code>int is_float_key(int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1433</i>
	 */
	public static native int is_float_key(int type);
	/**
	 * Original signature : <code>rangesrv_list* get_range_servers_from_stats(mdhim_t*, index_t*, void*, int, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1435</i>
	 */
	public static Pointer<rangesrv_list > get_range_servers_from_stats(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<? > key, int key_len, int op) {
		return (Pointer)Pointer.pointerToAddress(get_range_servers_from_stats(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(key), key_len, op), rangesrv_list.class);
	}
	@Ptr 
	protected native static long get_range_servers_from_stats(@Ptr long md, @Ptr long index, @Ptr long key, int key_len, int op);
	/**
	 * MPI MLOG levels<br>
	 * Original signature : <code>mdhim_rm_t* _put_record(mdhim_t*, index_t*, void*, int, void*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_private.h:1520</i>
	 */
	public static Pointer<mdhim_rm_t > _put_record(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<? > key, int key_len, Pointer<? > value, int value_len) {
		return (Pointer)Pointer.pointerToAddress(_put_record(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(key), key_len, Pointer.getPeer(value), value_len), mdhim_rm_t.class);
	}
	@Ptr 
	protected native static long _put_record(@Ptr long md, @Ptr long index, @Ptr long key, int key_len, @Ptr long value, int value_len);
	/**
	 * Original signature : <code>mdhim_brm_t* _create_brm(mdhim_rm_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_private.h:1522</i>
	 */
	public static Pointer<mdhim_brm_t > _create_brm(Pointer<mdhim_rm_t > rm) {
		return (Pointer)Pointer.pointerToAddress(_create_brm(Pointer.getPeer(rm)), mdhim_brm_t.class);
	}
	@Ptr 
	protected native static long _create_brm(@Ptr long rm);
	/**
	 * Original signature : <code>void _concat_brm(mdhim_brm_t*, mdhim_brm_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_private.h:1524</i>
	 */
	public static void _concat_brm(Pointer<mdhim_brm_t > head, Pointer<mdhim_brm_t > new$) {
		_concat_brm(Pointer.getPeer(head), Pointer.getPeer(new$));
	}
	protected native static void _concat_brm(@Ptr long head, @Ptr long new$);
	/**
	 * Original signature : <code>mdhim_brm_t* _bput_records(mdhim_t*, index_t*, void**, int*, void**, int*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_private.h:1526</i>
	 */
	public static Pointer<mdhim_brm_t > _bput_records(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<Pointer<? > > keys, Pointer<Integer > key_lens, Pointer<Pointer<? > > values, Pointer<Integer > value_lens, int num_records) {
		return (Pointer)Pointer.pointerToAddress(_bput_records(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(keys), Pointer.getPeer(key_lens), Pointer.getPeer(values), Pointer.getPeer(value_lens), num_records), mdhim_brm_t.class);
	}
	@Ptr 
	protected native static long _bput_records(@Ptr long md, @Ptr long index, @Ptr long keys, @Ptr long key_lens, @Ptr long values, @Ptr long value_lens, int num_records);
	/**
	 * Original signature : <code>mdhim_bgetrm_t* _bget_records(mdhim_t*, index_t*, void**, int*, int, int, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_private.h:1528</i>
	 */
	public static Pointer<mdhim_bgetrm_t > _bget_records(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<Pointer<? > > keys, Pointer<Integer > key_lens, int num_keys, int num_records, int op) {
		return (Pointer)Pointer.pointerToAddress(_bget_records(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(keys), Pointer.getPeer(key_lens), num_keys, num_records, op), mdhim_bgetrm_t.class);
	}
	@Ptr 
	protected native static long _bget_records(@Ptr long md, @Ptr long index, @Ptr long keys, @Ptr long key_lens, int num_keys, int num_records, int op);
	/**
	 * Original signature : <code>mdhim_brm_t* _bdel_records(mdhim_t*, index_t*, void**, int*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim_private.h:1530</i>
	 */
	public static Pointer<mdhim_brm_t > _bdel_records(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<Pointer<? > > keys, Pointer<Integer > key_lens, int num_records) {
		return (Pointer)Pointer.pointerToAddress(_bdel_records(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(keys), Pointer.getPeer(key_lens), num_records), mdhim_brm_t.class);
	}
	@Ptr 
	protected native static long _bdel_records(@Ptr long md, @Ptr long index, @Ptr long keys, @Ptr long key_lens, int num_records);
	/**
	 * Original signature : <code>mdhim_t* mdhimInit(void*, mdhim_options_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1567</i>
	 */
	public static Pointer<mdhim_t > mdhimInit(Pointer<? > appComm, Pointer<mdhim_options_t > opts) {
		return (Pointer)Pointer.pointerToAddress(mdhimInit(Pointer.getPeer(appComm), Pointer.getPeer(opts)), mdhim_t.class);
	}
	@Ptr 
	protected native static long mdhimInit(@Ptr long appComm, @Ptr long opts);
	/**
	 * Original signature : <code>int mdhimClose(mdhim_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1569</i>
	 */
	public static int mdhimClose(Pointer<mdhim_t > md) {
		return mdhimClose(Pointer.getPeer(md));
	}
	protected native static int mdhimClose(@Ptr long md);
	/**
	 * Original signature : <code>int mdhimCommit(mdhim_t*, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1571</i>
	 */
	public static int mdhimCommit(Pointer<mdhim_t > md, Pointer<index_t > index) {
		return mdhimCommit(Pointer.getPeer(md), Pointer.getPeer(index));
	}
	protected native static int mdhimCommit(@Ptr long md, @Ptr long index);
	/**
	 * Original signature : <code>int mdhimStatFlush(mdhim_t*, index_t*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1573</i>
	 */
	public static int mdhimStatFlush(Pointer<mdhim_t > md, Pointer<index_t > index) {
		return mdhimStatFlush(Pointer.getPeer(md), Pointer.getPeer(index));
	}
	protected native static int mdhimStatFlush(@Ptr long md, @Ptr long index);
	/**
	 * Original signature : <code>mdhim_brm_t* mdhimPut(mdhim_t*, void*, int, void*, int, secondary_info*, secondary_info*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1575</i>
	 */
	public static Pointer<mdhim_brm_t > mdhimPut(Pointer<mdhim_t > md, Pointer<? > key, int key_len, Pointer<? > value, int value_len, Pointer<secondary_info > secondary_global_info, Pointer<secondary_info > secondary_local_info) {
		return (Pointer)Pointer.pointerToAddress(mdhimPut(Pointer.getPeer(md), Pointer.getPeer(key), key_len, Pointer.getPeer(value), value_len, Pointer.getPeer(secondary_global_info), Pointer.getPeer(secondary_local_info)), mdhim_brm_t.class);
	}
	@Ptr 
	protected native static long mdhimPut(@Ptr long md, @Ptr long key, int key_len, @Ptr long value, int value_len, @Ptr long secondary_global_info, @Ptr long secondary_local_info);
	/**
	 * Original signature : <code>mdhim_brm_t* mdhimPutSecondary(mdhim_t*, index_t*, void*, int, void*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1577</i>
	 */
	public static Pointer<mdhim_brm_t > mdhimPutSecondary(Pointer<mdhim_t > md, Pointer<index_t > secondary_index, Pointer<? > secondary_key, int secondary_key_len, Pointer<? > primary_key, int primary_key_len) {
		return (Pointer)Pointer.pointerToAddress(mdhimPutSecondary(Pointer.getPeer(md), Pointer.getPeer(secondary_index), Pointer.getPeer(secondary_key), secondary_key_len, Pointer.getPeer(primary_key), primary_key_len), mdhim_brm_t.class);
	}
	@Ptr 
	protected native static long mdhimPutSecondary(@Ptr long md, @Ptr long secondary_index, @Ptr long secondary_key, int secondary_key_len, @Ptr long primary_key, int primary_key_len);
	/**
	 * Original signature : <code>mdhim_brm_t* mdhimBPut(mdhim_t*, void**, int*, void**, int*, int, secondary_bulk_info*, secondary_bulk_info*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1579</i>
	 */
	public static Pointer<mdhim_brm_t > mdhimBPut(Pointer<mdhim_t > md, Pointer<Pointer<? > > primary_keys, Pointer<Integer > primary_key_lens, Pointer<Pointer<? > > primary_values, Pointer<Integer > primary_value_lens, int num_records, Pointer<secondary_bulk_info > secondary_global_info, Pointer<secondary_bulk_info > secondary_local_info) {
		return (Pointer)Pointer.pointerToAddress(mdhimBPut(Pointer.getPeer(md), Pointer.getPeer(primary_keys), Pointer.getPeer(primary_key_lens), Pointer.getPeer(primary_values), Pointer.getPeer(primary_value_lens), num_records, Pointer.getPeer(secondary_global_info), Pointer.getPeer(secondary_local_info)), mdhim_brm_t.class);
	}
	@Ptr 
	protected native static long mdhimBPut(@Ptr long md, @Ptr long primary_keys, @Ptr long primary_key_lens, @Ptr long primary_values, @Ptr long primary_value_lens, int num_records, @Ptr long secondary_global_info, @Ptr long secondary_local_info);
	/**
	 * Original signature : <code>mdhim_bgetrm_t* mdhimGet(mdhim_t*, index_t*, void*, int, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1581</i>
	 */
	public static Pointer<mdhim_bgetrm_t > mdhimGet(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<? > key, int key_len, int op) {
		return (Pointer)Pointer.pointerToAddress(mdhimGet(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(key), key_len, op), mdhim_bgetrm_t.class);
	}
	@Ptr 
	protected native static long mdhimGet(@Ptr long md, @Ptr long index, @Ptr long key, int key_len, int op);
	/**
	 * Original signature : <code>mdhim_bgetrm_t* mdhimBGet(mdhim_t*, index_t*, void**, int*, int, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1583</i>
	 */
	public static Pointer<mdhim_bgetrm_t > mdhimBGet(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<Pointer<? > > keys, Pointer<Integer > key_lens, int num_records, int op) {
		return (Pointer)Pointer.pointerToAddress(mdhimBGet(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(keys), Pointer.getPeer(key_lens), num_records, op), mdhim_bgetrm_t.class);
	}
	@Ptr 
	protected native static long mdhimBGet(@Ptr long md, @Ptr long index, @Ptr long keys, @Ptr long key_lens, int num_records, int op);
	/**
	 * Original signature : <code>mdhim_bgetrm_t* mdhimBGetOp(mdhim_t*, index_t*, void*, int, int, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1585</i>
	 */
	public static Pointer<mdhim_bgetrm_t > mdhimBGetOp(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<? > key, int key_len, int num_records, int op) {
		return (Pointer)Pointer.pointerToAddress(mdhimBGetOp(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(key), key_len, num_records, op), mdhim_bgetrm_t.class);
	}
	@Ptr 
	protected native static long mdhimBGetOp(@Ptr long md, @Ptr long index, @Ptr long key, int key_len, int num_records, int op);
	/**
	 * Original signature : <code>mdhim_brm_t* mdhimDelete(mdhim_t*, index_t*, void*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1587</i>
	 */
	public static Pointer<mdhim_brm_t > mdhimDelete(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<? > key, int key_len) {
		return (Pointer)Pointer.pointerToAddress(mdhimDelete(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(key), key_len), mdhim_brm_t.class);
	}
	@Ptr 
	protected native static long mdhimDelete(@Ptr long md, @Ptr long index, @Ptr long key, int key_len);
	/**
	 * Original signature : <code>mdhim_brm_t* mdhimBDelete(mdhim_t*, index_t*, void**, int*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1589</i>
	 */
	public static Pointer<mdhim_brm_t > mdhimBDelete(Pointer<mdhim_t > md, Pointer<index_t > index, Pointer<Pointer<? > > keys, Pointer<Integer > key_lens, int num_keys) {
		return (Pointer)Pointer.pointerToAddress(mdhimBDelete(Pointer.getPeer(md), Pointer.getPeer(index), Pointer.getPeer(keys), Pointer.getPeer(key_lens), num_keys), mdhim_brm_t.class);
	}
	@Ptr 
	protected native static long mdhimBDelete(@Ptr long md, @Ptr long index, @Ptr long keys, @Ptr long key_lens, int num_keys);
	/**
	 * Original signature : <code>void mdhim_release_recv_msg(void*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1591</i>
	 */
	public static void mdhim_release_recv_msg(Pointer<? > msg) {
		mdhim_release_recv_msg(Pointer.getPeer(msg));
	}
	protected native static void mdhim_release_recv_msg(@Ptr long msg);
	/**
	 * Original signature : <code>secondary_info* mdhimCreateSecondaryInfo(index_t*, void**, int*, int, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1593</i>
	 */
	public static Pointer<secondary_info > mdhimCreateSecondaryInfo(Pointer<index_t > secondary_index, Pointer<Pointer<? > > secondary_keys, Pointer<Integer > secondary_key_lens, int num_keys, int info_type) {
		return (Pointer)Pointer.pointerToAddress(mdhimCreateSecondaryInfo(Pointer.getPeer(secondary_index), Pointer.getPeer(secondary_keys), Pointer.getPeer(secondary_key_lens), num_keys, info_type), secondary_info.class);
	}
	@Ptr 
	protected native static long mdhimCreateSecondaryInfo(@Ptr long secondary_index, @Ptr long secondary_keys, @Ptr long secondary_key_lens, int num_keys, int info_type);
	/**
	 * Original signature : <code>void mdhimReleaseSecondaryInfo(secondary_info*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1595</i>
	 */
	public static void mdhimReleaseSecondaryInfo(Pointer<secondary_info > si) {
		mdhimReleaseSecondaryInfo(Pointer.getPeer(si));
	}
	protected native static void mdhimReleaseSecondaryInfo(@Ptr long si);
	/**
	 * Original signature : <code>secondary_bulk_info* mdhimCreateSecondaryBulkInfo(index_t*, void***, int**, int*, int)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1597</i>
	 */
	public static Pointer<secondary_bulk_info > mdhimCreateSecondaryBulkInfo(Pointer<index_t > secondary_index, Pointer<Pointer<Pointer<? > > > secondary_keys, Pointer<Pointer<Integer > > secondary_key_lens, Pointer<Integer > num_keys, int info_type) {
		return (Pointer)Pointer.pointerToAddress(mdhimCreateSecondaryBulkInfo(Pointer.getPeer(secondary_index), Pointer.getPeer(secondary_keys), Pointer.getPeer(secondary_key_lens), Pointer.getPeer(num_keys), info_type), secondary_bulk_info.class);
	}
	@Ptr 
	protected native static long mdhimCreateSecondaryBulkInfo(@Ptr long secondary_index, @Ptr long secondary_keys, @Ptr long secondary_key_lens, @Ptr long num_keys, int info_type);
	/**
	 * Original signature : <code>void mdhimReleaseSecondaryBulkInfo(secondary_bulk_info*)</code><br>
	 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1599</i>
	 */
	public static void mdhimReleaseSecondaryBulkInfo(Pointer<secondary_bulk_info > si) {
		mdhimReleaseSecondaryBulkInfo(Pointer.getPeer(si));
	}
	protected native static void mdhimReleaseSecondaryBulkInfo(@Ptr long si);
	public int max_rangesrvs() {
		try {
			return (int)BridJ.getNativeLibrary("mdhim").getSymbolPointer("max_rangesrvs").as(int.class).get();
		}catch (Throwable $ex$) {
			throw new RuntimeException($ex$);
		}
	}
	public MdhimLibrary max_rangesrvs(int max_rangesrvs) {
		try {
			{
				BridJ.getNativeLibrary("mdhim").getSymbolPointer("max_rangesrvs").as(int.class).set(max_rangesrvs);
				return this;
			}
		}catch (Throwable $ex$) {
			throw new RuntimeException($ex$);
		}
	}
	/** Undefined type */
	public static interface UT_hash_handle {
		
	};
	/** Undefined type */
	public static interface index {
		
	};
	/** Undefined type */
	public static interface MPI_Request {
		
	};
	/** Undefined type */
	public static interface MPI_Comm {
		
	};
}
