package mdhim;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Used for storing stats in the database<br>
 * <i>native declaration : mdhim-tng-ycsb/src/data_store.h:1009</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public class mdhim_db_stat extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int slice() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public mdhim_db_stat slice(int slice) {
		this.io.setIntField(this, 0, slice);
		return this;
	}
	@Field(1) 
	public long imax() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public mdhim_db_stat imax(long imax) {
		this.io.setLongField(this, 1, imax);
		return this;
	}
	@Field(2) 
	public long imin() {
		return this.io.getLongField(this, 2);
	}
	@Field(2) 
	public mdhim_db_stat imin(long imin) {
		this.io.setLongField(this, 2, imin);
		return this;
	}
	@Field(3) 
	public double dmax() {
		return this.io.getDoubleField(this, 3);
	}
	@Field(3) 
	public mdhim_db_stat dmax(double dmax) {
		this.io.setDoubleField(this, 3, dmax);
		return this;
	}
	@Field(4) 
	public double dmin() {
		return this.io.getDoubleField(this, 4);
	}
	@Field(4) 
	public mdhim_db_stat dmin(double dmin) {
		this.io.setDoubleField(this, 4, dmin);
		return this;
	}
	@Field(5) 
	public long num() {
		return this.io.getLongField(this, 5);
	}
	@Field(5) 
	public mdhim_db_stat num(long num) {
		this.io.setLongField(this, 5, num);
		return this;
	}
	public mdhim_db_stat() {
		super();
	}
	public mdhim_db_stat(Pointer pointer) {
		super(pointer);
	}
}
