package mdhim;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : mdhim-tng-ycsb/src/partitioner.h:1412</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public class rangesrv_list extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : rangesrv_info* */
	@Field(0) 
	public Pointer<rangesrv_info > ri() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : rangesrv_info* */
	@Field(0) 
	public rangesrv_list ri(Pointer<rangesrv_info > ri) {
		this.io.setPointerField(this, 0, ri);
		return this;
	}
	/** C type : rangesrv_list* */
	@Field(1) 
	public Pointer<rangesrv_list > next() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : rangesrv_list* */
	@Field(1) 
	public rangesrv_list next(Pointer<rangesrv_list > next) {
		this.io.setPointerField(this, 1, next);
		return this;
	}
	public rangesrv_list() {
		super();
	}
	public rangesrv_list(Pointer pointer) {
		super(pointer);
	}
}
