package mdhim;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Range server info  <br>
 * Contains information about each range server<br>
 * <i>native declaration : mdhim-tng-ycsb/src/indexes.h:1278</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public abstract class rangesrv_info extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int rank() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public rangesrv_info rank(int rank) {
		this.io.setIntField(this, 0, rank);
		return this;
	}
	@Field(1) 
	public int rangesrv_num() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public rangesrv_info rangesrv_num(int rangesrv_num) {
		this.io.setIntField(this, 1, rangesrv_num);
		return this;
	}
	/** Conversion Error : UT_hash_handle (failed to convert type to Java (undefined type)) */
}
