package mdhim;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : mdhim-tng-ycsb/src/mdhim.h:1565</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mdhim") 
public class secondary_bulk_info extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : index_t* */
	@Field(0) 
	public Pointer<index_t > secondary_index() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : index_t* */
	@Field(0) 
	public secondary_bulk_info secondary_index(Pointer<index_t > secondary_index) {
		this.io.setPointerField(this, 0, secondary_index);
		return this;
	}
	/** C type : void*** */
	@Field(1) 
	public Pointer<Pointer<Pointer<? > > > secondary_keys() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : void*** */
	@Field(1) 
	public secondary_bulk_info secondary_keys(Pointer<Pointer<Pointer<? > > > secondary_keys) {
		this.io.setPointerField(this, 1, secondary_keys);
		return this;
	}
	/** C type : int** */
	@Field(2) 
	public Pointer<Pointer<Integer > > secondary_key_lens() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : int** */
	@Field(2) 
	public secondary_bulk_info secondary_key_lens(Pointer<Pointer<Integer > > secondary_key_lens) {
		this.io.setPointerField(this, 2, secondary_key_lens);
		return this;
	}
	/** C type : int* */
	@Field(3) 
	public Pointer<Integer > num_keys() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : int* */
	@Field(3) 
	public secondary_bulk_info num_keys(Pointer<Integer > num_keys) {
		this.io.setPointerField(this, 3, num_keys);
		return this;
	}
	@Field(4) 
	public int info_type() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public secondary_bulk_info info_type(int info_type) {
		this.io.setIntField(this, 4, info_type);
		return this;
	}
	public secondary_bulk_info() {
		super();
	}
	public secondary_bulk_info(Pointer pointer) {
		super(pointer);
	}
}
