MPI_ROOT        = /users/hng
LEVEL_DB_ROOT   = /users/hng/leveldb-1.12.0
C      = mpicc -g -O0 -Wall
CLIBS   = -L${MPI_ROOT}/lib -L${LEVEL_DB_ROOT}
CINC    = -I${MPI_ROOT}/include -I${LEVEL_DB_ROOT}/include -IMlog/ -Iuthash
CFLAGS  = -lmpich -lmdhim -lm -lpthread -lstdc++ ${LEVEL_DB_ROOT}/libleveldb.a
