#Configure your options here
#MPI_ROOT        = /usr/projects/plfs/rrz/mvapich2-1.9-gnu
#MPI_ROOT        = /turquoise/usr/projects/plfs/rrz/mvapich2-1.9-gnu-plfs-2.5-mdhim
MPI_ROOT        = /turquoise/usr/projects/plfs/rrz/mvapich-plfs-mdhim-dyn/install
#MPI_ROOT        = /opt/mvapich2-gnu-ofa-1.7
LEVEL_DB_ROOT   = /usr/projects/plfs/rrz/mdhim/leveldb/leveldb-1.15.0
#ROCKS_DB_ROOT   = /users/hng/rocksdb-2.6.fb
#MYSQL_DB_ROOT 	= /usr/include/mysql
LEVELDB = 1
ROCKSDB = 0
MYSQLDB = 0
CC      = mpicc -g -O0 -Wall -fPIC
#CC      = mpicc -g -O0 -Wall



#You shouldn't have to modify anything below
CLIBS   = -L$(MPI_ROOT)/lib
CINC    = -I$(MPI_ROOT)/include -IMlog2/ -Iuthash
CFLAGS  = -lmpich -lmdhim -lm -lpthread -lstdc++
ifeq ($(LEVELDB),1)
  CLIBS += -L$(LEVEL_DB_ROOT) -DLEVELDB_SUPPORT
  CINC += -I$(LEVEL_DB_ROOT)/include
  CFLAGS += $(LEVEL_DB_ROOT)/libleveldb.so.1.15
endif

ifeq ($(ROCKSDB),1)
  CLIBS += -L$(ROCKS_DB_ROOT) -DROCKSDB_SUPPORT
  CINC += -I$(ROCKS_DB_ROOT)/include
  CFLAGS += -lsnappy -lbz2 $(ROCKS_DB_ROOT)/librocksdb.a
endif


ifeq ($(MYSQLDB),1)
  CLIBS += -L/usr/lib/mysql -DMYSQLDB_SUPPORT
  CINC += -I/usr/include/mysql 
  CFLAGS += `mysql_config --cflags --libs` --std=c99
endif
